name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup node and yarn
      uses: actions/setup-node@v3
      with:
        cache: yarn
    - name: Yarn install
      # https://stackoverflow.com/a/69984661
      run: |
        if [ -e yarn.lock ]; then
        yarn install --frozen-lockfile
        elif [ -e package-lock.json ]; then
        npm ci
        else
        npm i
        fi
      shell: bash
    - run: yarn test

